### ISSUE TITLE
[REQ] Welcome message for VIP

### ISSUE THREAD

**Issue by crashzk** [1Mack/CS2-VipManager#1]
Firstly congratulations on the plugin, taking a look at it I see a good future for it. Why not a new VIP Core and its modules for CSSharp 🙅

With that, I leave a request for support to configure a welcome message for players who have VIP. In other words, VIP connected to the server will receive a message.

Message with support for line breaks and colors.

**Comment by 1Mack** [comment]
Sadly CSS does not support includes like sourcemod. When I have time i will take a look on it to see if there is other solution.

But for now you can use https://github.com/DeadSwimek/cs2-vip/ for vip perks.

I don't think it's a good idea to implement welcome message, because if you use another welcome plugin like https://github.com/savageservidores/ConnectInfo, it will conflit (2 messages for VIP).

So Instead of implementing a welcome message on my plugin, i will create a specific plugin for it, with VIP support.

**Comment by crashzk** [comment]
> Sadly CSS does not support includes like sourcemod. When I have time i will take a look on it to see if there is other solution.

I understand.

> I don't think it's a good idea to implement welcome message, because if you use another welcome plugin like https://github.com/savageservidores/ConnectInfo, it will conflit (2 messages for VIP).

I believe that a simple solution for this would be the option to activate this feature or not. If you want to use the welcome message, just type the message you want to display, leaving it empty will not send anything.

**Comment by 1Mack** [comment]
I'm working on it @crashzk 


(Plus) Message support with colors and permissions.

**Comment by 1Mack** [comment]
https://github.com/1Mack/CS2-VipManager/commit/53b7232d300d9a4bb8e2be33ae0179def9456302

**Comment by crashzk** [comment]
@1Mack just feedback... Could it be that now with [Dependency Injection](https://docs.cssharp.dev/guides/dependency-injection) we can expect plugins with include support? As I mentioned before, VIP Manager being the core and creating plugins/modules separately that only work with VIP Manager, like CSGO VIP Core.

**Comment by 1Mack** [comment]
I have to take a look on it...to see how it works, but thats a good idea
